import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav(){
  return <nav className="flex justify-between p-4 mb-4 items-center border-b">
    <div className="text-2xl font-semibold"> Gallery</div>
    <div className="text-2xl font-semibold">Sign In</div>
  </nav>
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} flex flex-col gap-4`}>
      
      <body>
      <TopNav/>
        {children}
      </body>
    </html>
  );
}
